### ISSUE TITLE
May 5th... 2021?

### ISSUE THREAD

**Issue by ElMatella** [algolia/algolia-coding-contest#2]
Hey! Thank you for the opportunity, I see that the time limit of the contest is may the 5th, is this 2021?

I just saw the project and I'm interested in it, but I can't build something cool in one week I think...

Anyways, are you going to showcase the different projects in the contest?

Thank you for your responses!

**Comment by juliereboul** [comment]
Hello, yes the deadline is on May 5th 2021. Sorry I didn't see the issue as it was closed!
I hope you're able to submit something, you can use a pre-existing project of yours and add Algolia to it for example.

Thanks and good luck!

**Comment by juliereboul** [comment]
Hello, yes the deadline is on May 5th 2021. Sorry I didn't see the issue as it was closed!
I hope you're able to submit something, you can use a pre-existing project of yours and add Algolia to it for example.

Thanks and good luck!
